# Generated by Django 4.2.1 on 2023-06-02 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=12)),
                ('email', models.EmailField(max_length=100)),
                ('active', models.BooleanField()),
            ],
        ),
    ]
