# Generated by Django 4.2.1 on 2023-06-02 06:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course', '0001_initial'),
        ('trainee', '0002_delete_trainee'),
    ]

    operations = [
        migrations.CreateModel(
            name='trainee',
            fields=[
                ('trainee_id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('Trainee_name', models.CharField(default='trainee', max_length=40)),
                ('email', models.EmailField(default='trainee@gmail.com', max_length=100)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.course')),
            ],
        ),
    ]
